[config]
transactions = 1000000
account = "pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA"
commitment = "processed"

[[endpoint]]
name = "Geyser"
url = "http://207.90.225.252:9999"
kind = "shredstream"

[[endpoint]]
name = "Bloxroute"
url = "http:/207.90.225.162:9999"
kind = "shredstream"
