[config]
transactions = 10000
account = "pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA"
commitment = "processed"

[[endpoint]]
name = "Orbit"
url = "http://207.90.225.163:9999"
kind = "shredstream"
#url = "http://ams.jetstream.orbitflare.com:80"
#kind = "jetstream"

[[endpoint]]
name = "Redacted"
#url = "http://198.13.130.155:9999"
url = "http://207.90.225.252:9999"
#url = "http://207.90.225.252:10000"
kind = "shredstream"
#kind = "yellowstone"
