[config]
transactions = 1000
account = "pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA"
commitment = "processed"

[[endpoint]]
name = "Metal 2"
url = "http://207.90.226.250:10000"
kind = "yellowstone"

[[endpoint]]
name = "Geyser"
url = "http://207.90.226.252:10000"
kind = "yellowstone"
