[config]
transactions = 1000
account = "pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA"
commitment = "processed"

[[endpoint]]
name = "Jito Shredstream""
url = "http://207.90.226.252:9999"
kind = "shredstream"

[[endpoint]]
name = "Geyser"
url = "http://207.90.226.252:10000"
kind = "yellowstone"
